### ISSUE TITLE
Presentation about Creativity from PyCon Italia missing in the presentations section

### ISSUE THREAD

**Issue by LenzGr** [fghaas/fghaas.github.io#10]
# Summary

I'm missing a link to your PyCon presentation about [Creativity - How we lost it, why that's bad, and how we get it back](https://xahteiwi.eu/pyconit2023/) in the [presentations section](https://xahteiwi.eu/category/presentations.html) of your blog.

## Where I found this problem

https://xahteiwi.eu/category/presentations.html

## How this should be fixed

Create a page that links to https://xahteiwi.eu/pyconit2023/ looks like the correct solution.

**Comment by LenzGr** [comment]
If you'd like to include a link to the YouTube recording, here's a link including the time stamp at which it starts: https://www.youtube.com/live/nUmolZkWQIg?feature=share&t=22847

**Comment by fghaas** [comment]
I do appreciate the nudge! :) I hadn't forgotten about this one. I only wanted to wait until the edited videos would come out, which I had hoped would be Any Day Now.™ But I guess you're right; I could just include the link to the unedited stream recording, for the time being.

**Comment by LenzGr** [comment]
Thank you!
